package com.radial.fraudmanagement;

import java.util.ArrayList;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Audit implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private int totalScore;
   private java.util.List<com.radial.fraudmanagement.AuditTrail> auditTrail;

   public Audit()
   {
   }

   public int getTotalScore()
   {
       int scoreTotal = 0;
       if(null != getAuditTrail()) {
           for(AuditTrail trail: getAuditTrail()) {
               scoreTotal+=trail.getScore();
           }
       }
       this.totalScore = scoreTotal;
      return this.totalScore;
   }

   public void setTotalScore(int totalScore)
   {
      this.totalScore = totalScore;
   }

   public java.util.List<com.radial.fraudmanagement.AuditTrail> getAuditTrail()
   {
       if(null == this.auditTrail) {
           this.auditTrail = new ArrayList<AuditTrail>();
       }
      return this.auditTrail;
   }

   public void setAuditTrail(
         java.util.List<com.radial.fraudmanagement.AuditTrail> auditTrail)
   {
      this.auditTrail = auditTrail;
   }

   public Audit(int totalScore,
         java.util.List<com.radial.fraudmanagement.AuditTrail> auditTrail)
   {
      this.totalScore = totalScore;
      this.auditTrail = auditTrail;
   }

}