package com.radial.fraudmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AuditTrail implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String rule;
   private int score;
   private java.lang.String action;
   private java.lang.String notes;

   public AuditTrail()
   {
   }

   public java.lang.String getRule()
   {
      return this.rule;
   }

   public void setRule(java.lang.String rule)
   {
      this.rule = rule;
   }

   public int getScore()
   {
      return this.score;
   }

   public void setScore(int score)
   {
      this.score = score;
   }

   public java.lang.String getAction()
   {
      return this.action;
   }

   public void setAction(java.lang.String action)
   {
      this.action = action;
   }

   public java.lang.String getNotes()
   {
      return this.notes;
   }

   public void setNotes(java.lang.String notes)
   {
      this.notes = notes;
   }

   public AuditTrail(java.lang.String rule, int score,
         java.lang.String action, java.lang.String notes)
   {
      this.rule = rule;
      this.score = score;
      this.action = action;
      this.notes = notes;
   }

}