package com.radial.fraudmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PaymentCard implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String maskedCardNumber;
   private java.util.Date expireDate;
   private java.lang.String cardType;
   private java.lang.String cardHolderName;
   private java.lang.String cardNumber;

   public PaymentCard()
   {
   }

   public java.lang.String getMaskedCardNumber()
   {
      return this.maskedCardNumber;
   }

   public void setMaskedCardNumber(java.lang.String maskedCardNumber)
   {
      this.maskedCardNumber = maskedCardNumber;
   }

   public java.util.Date getExpireDate()
   {
      return this.expireDate;
   }

   public void setExpireDate(java.util.Date expireDate)
   {
      this.expireDate = expireDate;
   }

   public java.lang.String getCardType()
   {
      return this.cardType;
   }

   public void setCardType(java.lang.String cardType)
   {
      this.cardType = cardType;
   }

   public java.lang.String getCardHolderName()
   {
      return this.cardHolderName;
   }

   public void setCardHolderName(java.lang.String cardHolderName)
   {
      this.cardHolderName = cardHolderName;
   }

   public java.lang.String getCardNumber()
   {
      return this.cardNumber;
   }

   public void setCardNumber(java.lang.String cardNumber)
   {
      this.cardNumber = cardNumber;
   }

   public PaymentCard(java.lang.String maskedCardNumber,
         java.util.Date expireDate, java.lang.String cardType,
         java.lang.String cardHolderName, java.lang.String cardNumber)
   {
      this.maskedCardNumber = maskedCardNumber;
      this.expireDate = expireDate;
      this.cardType = cardType;
      this.cardHolderName = cardHolderName;
      this.cardNumber = cardNumber;
   }

}