package com.radial.fraudmanagement;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Telephone implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String phoneLocationType;
   private java.lang.String legacyPhoneNumber;

   public Telephone()
   {
   }

   public java.lang.String getPhoneLocationType()
   {
      return this.phoneLocationType;
   }

   public void setPhoneLocationType(java.lang.String phoneLocationType)
   {
      this.phoneLocationType = phoneLocationType;
   }

   public java.lang.String getLegacyPhoneNumber()
   {
      return this.legacyPhoneNumber;
   }

   public void setLegacyPhoneNumber(java.lang.String legacyPhoneNumber)
   {
      this.legacyPhoneNumber = legacyPhoneNumber;
   }

   public Telephone(java.lang.String phoneLocationType,
         java.lang.String legacyPhoneNumber)
   {
      this.phoneLocationType = phoneLocationType;
      this.legacyPhoneNumber = legacyPhoneNumber;
   }

}